### ISSUE TITLE
"Client already exists" when editing Client ID of existing entry

### ISSUE THREAD

**Issue by mrzxy** [jacekkow/keycloak-protocol-cas#28] opened 2021-05-19 05:39 UTC

**Comment by mrzxy** [comment] 2021-05-19 05:39
![image](https://user-images.githubusercontent.com/11501927/118761797-a9a2cc80-b8a7-11eb-86cb-b20dd266273b.png)

**Comment by jacekkow** [comment] 2021-05-19 22:09
You have selected "Client Protocol: openid-connect". This plugin is for "Client Protocol: cas" only.

The error message indicates you have duplicate Client ID. I don't know what you're trying to accomplish, but it seems it is not related to this plugin at all. Report any issues with Keycloak (not keycloak-protocol-cas) upstream.

**Comment by mrzxy** [comment] 2021-05-20 02:24
Sorry, I didn’t express it clearly. When I use this code repository, I will prompt this error when I create a new client. No matter whether the client Protocol is cas or saml, I also guarantee that my client id is unique. The incredible thing is that although the error is reported, client created successfully

![image](https://user-images.githubusercontent.com/11501927/118909340-79196c00-b955-11eb-8c5e-7118dd6603a4.png)

![image](https://user-images.githubusercontent.com/11501927/118909416-8df5ff80-b955-11eb-8357-b3f3ad91470e.png)

**Comment by jacekkow** [comment] 2021-05-21 22:50
I was able to reproduce it - but in the example above you are not creating a new client, you are *editing client ID* of existing entry.

**Comment by jacekkow** [comment] 2021-05-21 22:56
It might be related to https://issues.redhat.com/projects/KEYCLOAK/issues/KEYCLOAK-18244

**Comment by jacekkow** [comment] 2021-06-22 13:33
It looks like it was fixed in Keycloak 14 - could you verify it, too?

**Comment by jacekkow** [comment] 2021-08-10 17:58
I'm closing this issues, assuming it is fixed in the latest Keycloak version.

If you still encounter this issue, let me know.

**Closed by jacekkow** 2021-08-10 17:58 UTC
Labels: type: bug

**Comment by BradleyMBancX** [comment] 2024-07-31 21:09
you can get around this issue on Keycloak 13 by creating the client. Then export the json.

Edit this json config file to include the redirectURL you need. 

Then delete the client, and create a new one from importing the file
